# Generated by Django 5.2.5 on 2025-08-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_profile',
            new_name='profile_picture',
        ),
    ]
